name: Solo Documentacion en Develop

on:
  push:
    branches:
      - develop    # Filtro de rama: Solo reacciona a 'develop'
    paths:
      - 'docs/**'  # Filtro de ruta: Solo si cambian archivos en docs/

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Actualizando Documentaci√≥n
        run: echo "Se han detectado cambios en la carpeta docs de la rama develop. Procesando..."